version: '3'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_DATABASE: docker
      MARIADB_USER: docker
      MARIADB_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - db_network
  web:
    build: 
      context: .
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - ./web:/web
      - static_volume:/web/static
      - ./env/aws:/root/.aws
    ports:
      - 8000:8000
    depends_on:
      - db
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    networks:
      - web_network
      - db_network
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - web
    networks:
      - web_network
    volumes:
      - static_volume:/web/static

networks: 
    web_network:
      driver: bridge
    db_network:
      driver: bridge

volumes:
  static_volume:
